/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function CatModel({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/cat.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Quad_Sphere.geometry} material={materials.Material} />
    </group>
  )
}

useGLTF.preload('assets/cat.glb')
